version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
  craapp:
    image: ${DOCKER_REGISTRY-}craapp
    build:
      context: .
      dockerfile: CraApp/Dockerfile
  craapp.web:
    image: ${DOCKER_REGISTRY-}craappweb
    build:
      context: .
      dockerfile: CraApp.Web/Dockerfile

